const songs = [
{ artist:"a-ha", song:"Take on Me" },
{ artist:"ABBA", song:"Dancing Queen" },
{ artist:"ABBA", song:"Gimme! Gimme! Gimme!" },
{ artist:"ABBA", song:"Mamma Mia" },
{ artist:"Adele", song:"Rolling In The Deep" },
{ artist:"Aikakone", song:"Odota" },
{ artist:"Akon feat. Eminem", song:"Smack That" },
{ artist:"Alexander Rybak", song:"Fairytale" },
{ artist:"Amy Macdonald", song:"This Is The Life" },
{ artist:"Amy Winehouse", song:"Rehab" },
{ artist:"Amy Winehouse", song:"Valerie" },
{ artist:"Annika Eklund", song:"Shanghain Valot" },
{ artist:"Anssi Kela", song:"1972" },
{ artist:"Anssi Kela", song:"Milla" },
{ artist:"Antti Tuisku", song:"Hanuri" },
{ artist:"Antti Tuisku", song:"Rahan takii" },
{ artist:"Antti Tuisku", song:"Sata Salamaa" },
{ artist:"Antti Tuisku", song:"Treenaa" },
{ artist:"Antti Tuisku", song:"Valittu Kansa" },
{ artist:"Antti Tuisku feat. Käärijä", song:"Auto jää" },
{ artist:"Antti Tuisku feat. VilleGalle", song:"Keinutaan" },
{ artist:"ATC", song:"Around The World (La La La La La)" },
{ artist:"Aqua", song:"Barbie Girl" },
{ artist:"Arttu Wiskari", song:"Suomen Muotoisen Pilven Alla" },
{ artist:"Arttu Wiskari", song:"Sirpa" },
{ artist:"Arttu Wiskari feat. Leavings-orkesteri", song:"Tässäkö Tää Oli?" },
{ artist:"Avicii", song:"Levels" },
{ artist:"Avicii", song:"Wake Me Up" },
{ artist:"Avril Lavigne", song:"Sk8ter Boy" },
{ artist:"Backstreet Boys", song:"Everybody (Backstreet's Back)" },
{ artist:"Backstreet Boys", song:"I Want It That Way" },
{ artist:"Bee Gees", song:"Stayin’ Alive" },
{ artist:"Benjamin & Bess", song:"Paremmin ku kukaan muu" },
{ artist:"Bess", song:"Ram Pam Pam" },
{ artist:"Bess", song:"Tempo" },
{ artist:"Bess, Käärijä", song:"Kaistaa" },
{ artist:"Billy Joel", song:"Uptown Girl" },
{ artist:"Black Eyed Peas", song:"Boom Boom Pow" },
{ artist:"blink-182", song:"All the Small Things" },
{ artist:"Blondie", song:"Call Me" },
{ artist:"Bloodhound Gang", song:"The Bad Touch" },
{ artist:"Blur", song:"Song 2" },
{ artist:"Bobby Womack", song:"Across 110th Street" },
{ artist:"Bomfunk MC’s", song:"Freestyler" },
{ artist:"Bon Jovi", song:"It's My Life" },
{ artist:"Bon Jovi", song:"Livin' On A Prayer" },
{ artist:"Bon Jovi", song:"Runaway" },
{ artist:"Bon Jovi", song:"You Give Love A Bad Name" },
{ artist:"Britney Spears", song:"…Baby One More Time" },
{ artist:"Britney Spears", song:"Oops!... I Did It Again" },
{ artist:"Britney Spears", song:"Toxic" },
{ artist:"Britney Spears", song:"Womanizer" },
{ artist:"Bruno Mars", song:"24K Magic" },
{ artist:"Bruno Mars", song:"That's What I Like" },
{ artist:"Bruno Mars, Mark Ronson", song:"Uptown Funk" },
{ artist:"Bryan Adams", song:"Summer of ’69" },
{ artist:"Captain Jack", song:"Captain Jack" },
{ artist:"Carly Rae Jepsen", song:"Call Me Maybe" },
{ artist:"Carrie Underwood", song:"Before He Cheats" },
{ artist:"Cascada", song:"Everytime We Touch" },
{ artist:"Chappell Roan", song:"Pink Pony Club" },
{ artist:"Cheek", song:"Timantit On Ikuisia" },
{ artist:"Coldplay", song:"Viva La Vida" },
{ artist:"Corona", song:"Rhythm of the Night" },
{ artist:"Culture Beat", song:"Mr. Vain" },
{ artist:"Cyndi Lauper", song:"Girls Just Want To Have Fun" },
{ artist:"Daddy Yankee", song:"Gasolina" },
{ artist:"Daft Punk", song:"Get Lucky" },
{ artist:"David Guetta feat. Sia", song:"Titanium" },
{ artist:"Destiny's Child", song:"Say My Name" },
{ artist:"Destiny's Child", song:"Survivor" },
{ artist:"Dingo", song:"Autiotalo" },
{ artist:"Dingo", song:"Levoton Tuhkimo" },
{ artist:"DJ Ötzi", song:"Hey Baby" },
{ artist:"Donna Summer", song:"Hot Stuff" },
{ artist:"Dua Lipa", song:"Don't Start Now" },
{ artist:"Ed Sheeran", song:"Shape of You" },
{ artist:"Edward Maya & Vika Jigulina", song:"Stereo Love" },
{ artist:"Eiffel 65", song:"Blue" },
{ artist:"Eini", song:"Kesä Ja Yö" },
{ artist:"Elastinen", song:"Anna Soida" },
{ artist:"Eminem", song:"Lose Yourself" },
{ artist:"Eminem", song:"Without Me" },
{ artist:"Eppu Normaali", song:"Tahroja Paperilla" },
{ artist:"Eppu Normaali", song:"Vuonna ‘85" },
{ artist:"Erika Vikman", song:"Cicciolina" },
{ artist:"Erika Vikman", song:"Ich Komme" },
{ artist:"Erika Vikman", song:"Syntisten Pöytä" },
{ artist:"Europe", song:"The Final Countdown" },
{ artist:"Evelina", song:"Tornado" },
{ artist:"Fintelligens", song:"Mikä boogie" },
{ artist:"Flo Rida feat. T-Pain", song:"Low" },
{ artist:"Franz Ferdinand", song:"Take Me Out" },
{ artist:"Frederik", song:"Titanic" },
{ artist:"Frederik", song:"Kolmekymppinen" },
{ artist:"Gala", song:"Freed from Desire" },
{ artist:"Gasellit & JVG", song:"Mitä mä Malagas" },
{ artist:"Gloria Gaynor", song:"I Will Survive" },
{ artist:"Green Day", song:"American Idiot" },
{ artist:"Green Day", song:"Basket Case" },
{ artist:"Guns N’ Roses", song:"Paradise City" },
{ artist:"Günther", song:"Ding Dong Song" },
{ artist:"Guru Josh Project", song:"Infinity" },
{ artist:"Haddaway", song:"What Is Love" },
{ artist:"Haloo Helsinki!", song:"Beibi" },
{ artist:"Haloo Helsinki!", song:"Jos Mun Pokka Pettää" },
{ artist:"Haloo Helsinki!", song:"Maailman toisella puolen" },
{ artist:"Haloo Helsinki!", song:"Reiviluola" },
{ artist:"Harry Styles", song:"As It Was" },
{ artist:"Hassisen Kone", song:"Levottomat jalat" },
{ artist:"Hausmylly", song:"Ikävä Lokakuu" },
{ artist:"Hector", song:"Juodaan viinaa" },
{ artist:"Infernal", song:"From Paris to Berlin" },
{ artist:"Irina", song:"Kymmenen Kirosanaa" },
{ artist:"Irina", song:"Pokka" },
{ artist:"Indica", song:"Ikuinen Virta" },
{ artist:"Irwin Goodman", song:"Ei tippa tapa" },
{ artist:"Irwin Goodman", song:"Rentun ruusu" },
{ artist:"J. Karjalainen", song:"Mennyt mies" },
{ artist:"Jenni Vartiainen", song:"Ihmisten edessä" },
{ artist:"Jessie J", song:"Price Tag" },
{ artist:"Jet", song:"Are You Gonna Be My Girl" },
{ artist:"Joan Jett & the Blackhearts", song:"I Love Rock ‘n Roll" },
{ artist:"John Denver", song:"Take Me Home, Country Roads" },
{ artist:"Journey", song:"Don’t Stop Believin’" },
{ artist:"Juice Leskinen", song:"Viidestoista yö" },
{ artist:"Juice Leskinen", song:"Musta Aurinko Nousee" },
{ artist:"Justin Bieber feat. Nicki Minaj", song:"Beauty And A Beat" },
{ artist:"Justin Timberlake", song:"Can’t Stop the Feeling" },
{ artist:"Justin Timberlake", song:"SexyBack" },
{ artist:"JVG", song:"Amatimies" },
{ artist:"JVG", song:"Huominen On Huomenna" },
{ artist:"JVG", song:"Häissä" },
{ artist:"JVG", song:"Ikuinen Vappu" },
{ artist:"JVG", song:"Kran Turismo" },
{ artist:"JVG", song:"Mitä Mä Malagas" },
{ artist:"JVG", song:"Tarkenee" },
{ artist:"JVG", song:"Voitolla yöhön" },
{ artist:"KAJ", song:"Bara Bada Bastu" },
{ artist:"Kaija Koo", song:"Kaunis, Rietas, Onnellinen" },
{ artist:"Kaija Koo", song:"Supernaiset" },
{ artist:"Kaija Koo", song:"Tinakenkätyttö" },
{ artist:"Kaija Koo", song:"Vapaa" },
{ artist:"Kaija Koo feat. Cheek", song:"Nää Yöt Ei Anna Armoo" },
{ artist:"Karri Koira", song:"Lähe Mun Kaa" },
{ artist:"Katy Perry", song:"Firework" },
{ artist:"Katy Perry", song:"Teenage Dreams" },
{ artist:"Katy Perry", song:"Roar" },
{ artist:"Katy Perry feat. Snoop Dogg", song:"California Gurls" },
{ artist:"Kelly Clarkson", song:"Since U Been Gone" },
{ artist:"Kenny Loggins", song:"Footloose" },
{ artist:"Kesha", song:"Tik Tok" },
{ artist:"Kesha", song:"Die Young" },
{ artist:"Kikka", song:"Huone 105" },
{ artist:"Kikka", song:"Sukkula Venukseen" },
{ artist:"Kings of Leon", song:"Sex On Fire" },
{ artist:"Kirka", song:"Hengaillaan" },
{ artist:"Kirka", song:"Hetki lyö" },
{ artist:"Kirka", song:"Surun pyyhit silmistäni" },
{ artist:"Kiss", song:"I Was Made For Loving You" },
{ artist:"Klamydia", song:"Pienen pojan elämää" },
{ artist:"Klamydia", song:"Tytöt tykkää" },
{ artist:"KUUMAA", song:"Ylivoimainen" },
{ artist:"Kylie Minogue", song:"Can’t Get You Out of My Head" },
{ artist:"Käärijä", song:"Cha Cha Cha" },
{ artist:"Käärijä & Erika Vikman", song:"Ruoska" },
{ artist:"Lady Gaga", song:"Abracadabra" },
{ artist:"Lady Gaga", song:"Bad Romance" },
{ artist:"Lady Gaga", song:"Poker Face" },
{ artist:"Lapinlahden Linnut", song:"Vanha Suomalaisten Poikain Vitutuslaulu" },
{ artist:"Leevi and the Leavings", song:"Pohjois-Karjala" },
{ artist:"Leevi and the Leavings", song:"Teuvo" },
{ artist:"Leevi and the Leavings", song:"Pojat Tanssimaan" },
{ artist:"Leidit", song:"Hittiputki" },
{ artist:"LMFAO", song:"Party Rock Anthem" },
{ artist:"Los del Río", song:"Macarena" },
{ artist:"Loreen", song:"Euphoria" },
{ artist:"Lou Bega", song:"Mambo No. 5" },
{ artist:"Luis Fonsi feat. Daddy Yankee", song:"Despacito" },
{ artist:"Lynyrd Skynyrd", song:"Sweet Home Alabama" },
{ artist:"Macklemore & Ryan Lewis feat. Ray Dalton", song:"Can't Hold Us" },
{ artist:"Madonna", song:"Holiday" },
{ artist:"Madonna", song:"Hung Up" },
{ artist:"Madonna", song:"La Isla Bonita" },
{ artist:"Madonna", song:"Like A Prayer" },
{ artist:"Mamba", song:"Lauantai-ilta" },
{ artist:"Mamba", song:"Vielä on kesää jäljellä" },
{ artist:"Maroon 5 feat. Christina Aguilera", song:"Moves Like Jagger" },
{ artist:"Martti Vainaa & Sallitut Aineet", song:"Pelimies" },
{ artist:"Michael Jackson", song:"Beat It" },
{ artist:"Michael Jackson", song:"Billie Jean" },
{ artist:"Miley Cyrus", song:"Party In The USA" },
{ artist:"Miley Cyrus", song:"We Can't Stop" },
{ artist:"Mirella", song:"Timanttei" },
{ artist:"Modern Talking", song:"Cheri Cheri Lady" },
{ artist:"Modern Talking", song:"You're My Heart, You're My Soul" },
{ artist:"Movetron", song:"Romeo Ja Julia" },
{ artist:"Måneskin", song:"Beggin’" },
{ artist:"Natasha Bedingfield", song:"Pocketful Of Sunshine" },
{ artist:"Natasha Bedingfield", song:"Unwritten" },
{ artist:"Neil Diamond", song:"Sweet Caroline" },
{ artist:"Nelly", song:"Hot in Herre" },
{ artist:"Neon 2", song:"Kemiaa" },
{ artist:"Nirvana", song:"Smells Like Teen Spirit" },
{ artist:"Nylon Beat", song:"Rakastuin Mä Looseriin" },
{ artist:"Nylon Beat", song:"Satasen Laina" },
{ artist:"Nylon Beat", song:"Viimeinen" },
{ artist:"O-Zone", song:"Dragostea Din Tei" },
{ artist:"Outkast", song:"Hey Ya" },
{ artist:"Paula Koivuniemi", song:"Kun Kuuntelen Tomppaa" },
{ artist:"Paula Koivuniemi", song:"Paulapotpuri" },
{ artist:"Paula Koivuniemi", song:"Sata Kesää, Tuhat Yötä" },
{ artist:"Pate Mustajärvi ja Saara Soisalo", song:"Mä lähden stadiin" },
{ artist:"Pave Maijanen", song:"Lähtisitkö" },
{ artist:"Pelle Miljoona", song:"Moottoritie on kuuma" },
{ artist:"Pelle Miljoona", song:"Tahdon Rakastella Sinua" },
{ artist:"Pet Shop Boys", song:"Domino Dancing" },
{ artist:"Pet Shop Boys", song:"It's A Sin" },
{ artist:"Petri Nygård", song:"Reggaerekka" },
{ artist:"Petri Nygård", song:"Selvä päivä" },
{ artist:"Pilvi Hämäläinen", song:"Mon Chéri" },
{ artist:"Pitbull", song:"Hotel Room Service" },
{ artist:"PMMP", song:"Rusketusraidat" },
{ artist:"Poju", song:"Esson Baariin" },
{ artist:"Poju", song:"Poika saunoo" },
{ artist:"Popeda", song:"Kersantti Karoliina" },
{ artist:"Popeda", song:"Kuuma kesä" },
{ artist:"Popeda", song:"Matkalla Alabamaan" },
{ artist:"Popeda", song:"Repe Ja Lissu" },
{ artist:"Popeda", song:"Ukkometso" },
{ artist:"Portion Boys", song:"Elämän ABC" },
{ artist:"Portion Boys", song:"Kyläbaari" },
{ artist:"Portion Boys", song:"Nautin elämästä" },
{ artist:"Portion Boys feat. Kake Randelin", song:"Juhannusyö" },
{ artist:"Portion Boys feat. Matti ja Teppo", song:"Vauhti Kiihtyy" },
{ artist:"Pretenders", song:"Don't Get Me Wrong" },
{ artist:"PSY", song:"Gangnam Style" },
{ artist:"Queen", song:"Bohemian Rhapsody" },
{ artist:"Queen", song:"Don’t Stop Me Now" },
{ artist:"Queen", song:"I Want to Break Free" },
{ artist:"Queen", song:"Radio Gaga" },
{ artist:"Queen", song:"We Are the Champions" },
{ artist:"Queen", song:"We Will Rock You" },
{ artist:"Raappana", song:"Kauas Pois" },
{ artist:"Raappana feat. Sini Yasemin", song:"Chilii" },
{ artist:"Ramses II", song:"Villieläin" },
{ artist:"Raptori", song:"Oi Beibi" },
{ artist:"Rauli Badding Somerjoki", song:"Paratiisi" },
{ artist:"R.E.M.", song:"It’s The End Of The World As We Know It" },
{ artist:"Rednex", song:"Cotton Eye Joe" },
{ artist:"Rihanna", song:"Pon de Replay" },
{ artist:"Rihanna", song:"Umbrella" },
{ artist:"Rick Astley", song:"Never Gonna Give You Up" },
{ artist:"Robbie Williams", song:"Feel" },
{ artist:"Robbie Williams", song:"Let Me Entertain You" },
{ artist:"Robin", song:"Frontside Ollie" },
{ artist:"Robin S", song:"Show Me Love" },
{ artist:"Robyn", song:"Dancing On My Own" },
{ artist:"Roope Salminen & Koirat feat. Ida Paul", song:"Madafakin Darra" },
{ artist:"ROSÉ & Bruno Mars", song:"APT" },
{ artist:"Sabrina Carpenter", song:"Espresso" },
{ artist:"Sammy Babitzin", song:"Daa-Da Daa-Da" },
{ artist:"Scatman John", song:"Scatman" },
{ artist:"Sexmane", song:"Chillaa veli" },
{ artist:"Shakira", song:"Hips Don’t Lie" },
{ artist:"Sini Sabotage feat. VilleGalle", song:"Levikset Repee" },
{ artist:"Smash Mouth", song:"All Star" },
{ artist:"Snap!", song:"Rhythm Is a Dancer" },
{ artist:"Spekti", song:"Macho Fantastico" },
{ artist:"Spice Girls", song:"Wannabe" },
{ artist:"Stevie Wonder", song:"Part Time Lover" },
{ artist:"Survivor", song:"Eye of the Tiger" },
{ artist:"Suurlähettiläät", song:"Kun Tänään Lähden" },
{ artist:"Stig", song:"Roy Orbison" },
{ artist:"Stig", song:"Puumaa Mä Metsästän" },
{ artist:"Take That", song:"Relight My Fire" },
{ artist:"Tapani Kansa", song:"R-A-K-A-S" },
{ artist:"Teflon Brothers", song:"Maradona (Kesä -86)" },
{ artist:"Teflon Brothers feat. Illari Sahamies", song:"Pämppää" },
{ artist:"The Beatles", song:"Twist and Shout" },
{ artist:"The Doors", song:"Break On Through" },
{ artist:"The Doors", song:"Light My Fire" },
{ artist:"The Human League", song:"Don’t You Want Me" },
{ artist:"The Killers", song:"Mr. Brightside" },
{ artist:"The Weather Girls", song:"It's Raining Men" },
{ artist:"The Weeknd", song:"Blinding Lights" },
{ artist:"The White Stripes", song:"Seven Nation Army" },
{ artist:"Tiktak", song:"Lopeta" },
{ artist:"Tina Turner", song:"Nutbush City Limits" },
{ artist:"Tones And I", song:"Dance Monkey" },
{ artist:"Toploader", song:"Dancing in the Moonlight" },
{ artist:"Toto", song:"Africa" },
{ artist:"Travie McCoy feat. Bruno Mars", song:"Billionaire" },
{ artist:"Twisted Sister", song:"We’re Not Gonna Take It" },
{ artist:"Ultra Bra", song:"Sinä Lähdit Pois" },
{ artist:"Usher", song:"Yeah!" },
{ artist:"Valvomo", song:"Mikä kesä" },
{ artist:"Vance Joy", song:"Riptide" },
{ artist:"Vengaboys", song:"Boom, Boom, Boom, Boom" },
{ artist:"Vengaboys", song:"We Like To Party!" },
{ artist:"Vesala", song:"Älä droppaa mun tunnelmaa" },
{ artist:"Village People", song:"YMCA" },
{ artist:"Vilma Alina", song:"Juha88" },
{ artist:"Virve Rosti", song:"Oon Voimissain" },
{ artist:"Virve Rosti", song:"Sata Salamaa" },
{ artist:"Walk the Moon", song:"Shut Up and Dance" },
{ artist:"Wham!", song:"Wake Me Up Before You Go-Go" },
{ artist:"Wheatus", song:"Teenage Dirtbag" },
{ artist:"Whitney Houston", song:"I Wanna Dance With Somebody" }

];
