const songs = [
  { artist:"Avril Lavigne", song:"Complicated" },
  { artist:"Backstreet Boys", song:"Everybody (Backstreet's Back)" },
  { artist:"Backstreet Boys", song:"I Want It That Way" },
  { artist:"Bee Gees", song:"Stayin’ Alive" },
  { artist:"Benjamin & Bess", song:"Paremmin ku kukaan muu" },
  { artist:"Bess", song:"Ram Pam Pam" },
  { artist:"Bess", song:"Tempo" },
  { artist:"Bess, Käärijä", song:"Kaistaa" },
  { artist:"Billy Joel", song:"Uptown Girl" },
  { artist:"Black Eyed Peas", song:"Boom Boom Pow" },
  { artist:"blink-182", song:"All the Small Things" },
  { artist:"Blondie", song:"Call Me" },
  { artist:"Bloodhound Gang", song:"The Bad Touch" },
  { artist:"Blur", song:"Song 2" },
  { artist:"Bobby Womack", song:"Across 110th Street" },
  { artist:"Bomfunk MC’s", song:"Freestyler" },
  { artist:"Bon Jovi", song:"It's My Life" },
  { artist:"Bon Jovi", song:"Livin' On A Prayer" },
  { artist:"Bon Jovi", song:"Runaway" },
  { artist:"Bon Jovi", song:"You Give Love A Bad Name" },
  { artist:"Britney Spears", song:"…Baby One More Time" },
  { artist:"Britney Spears", song:"Oops!... I Did It Again" },
  { artist:"Britney Spears", song:"Toxic" },
  { artist:"Britney Spears", song:"Womanizer" },
  { artist:"Bruno Mars", song:"24K Magic" },
  { artist:"Bruno Mars", song:"That's What I Like" },
  { artist:"Bruno Mars, Mark Ronson", song:"Uptown Funk" },
  { artist:"Bryan Adams", song:"Summer of ’69" },
  { artist:"Captain Jack", song:"Captain Jack" },
  { artist:"Carly Rae Jepsen", song:"Call Me Maybe" },
  { artist:"Carrie Underwood", song:"Before He Cheats" },
  { artist:"Cascada", song:"Everytime We Touch" },
  { artist:"Chappell Roan", song:"Pink Pony Club" },
  { artist:"Cheek", song:"Timantit On Ikuisia" },
  { artist:"Coldplay", song:"Viva La Vida" },
  { artist:"Corona", song:"Rhythm of the Night" },
  { artist:"Culture Beat", song:"Mr. Vain" },
  { artist:"Cyndi Lauper", song:"Girls Just Want To Have Fun" },
  { artist:"Daddy Yankee", song:"Gasolina" },
  { artist:"Daft Punk", song:"Get Lucky" },
  { artist:"David Guetta feat. Sia", song:"Titanium" },
  { artist:"Destiny's Child", song:"Say My Name" },
  { artist:"Destiny's Child", song:"Survivor" },
  { artist:"Dingo", song:"Autiotalo" },
  { artist:"Dingo", song:"Levoton Tuhkimo" },
  { artist:"DJ Ötzi", song:"Hey Baby" },
  { artist:"Donna Summer", song:"Hot Stuff" },
  { artist:"Dua Lipa", song:"Don't Start Now" },
  { artist:"Ed Sheeran", song:"Shape of You" },
  { artist:"Edward Maya & Vika Jigulina", song:"Stereo Love" },
  { artist:"Eiffel 65", song:"Blue" },
  { artist:"Eini", song:"Kesä Ja Yö" },
  { artist:"Elastinen", song:"Anna Soida" },
  { artist:"Eminem", song:"Lose Yourself" },
  { artist:"Eminem", song:"Without Me" },
  { artist:"Eppu Normaali", song:"Tahroja Paperilla" },
  { artist:"Eppu Normaali", song:"Vuonna ‘85" },
  { artist:"Erika Vikman", song:"Cicciolina" },
  { artist:"Erika Vikman", song:"Ich Komme" },
  { artist:"Erika Vikman", song:"Syntisten Pöytä" },
  { artist:"Europe", song:"The Final Countdown" },
  { artist:"Evelina", song:"Tornado" },
  { artist:"Fintelligens", song:"Mikä boogie" },
  { artist:"Flo Rida feat. T-Pain", song:"Low" },
  { artist:"Franz Ferdinand", song:"Take Me Out" },
  { artist:"Frederik", song:"Titanic" },
  { artist:"Frederik", song:"Kolmekymppinen" },
  { artist:"Gala", song:"Freed from Desire" },
  { artist:"Gasellit & JVG", song:"Mitä mä Malagas" },
  { artist:"Gloria Gaynor", song:"I Will Survive" },
  { artist:"Green Day", song:"American Idiot" },
  { artist:"Green Day", song:"Basket Case" },
  { artist:"Guns N’ Roses", song:"Paradise City" },
  { artist:"Günther", song:"Ding Dong Song" },
  { artist:"Guru Josh Project", song:"Infinity" },
  { artist:"Haddaway", song:"What Is Love" },
  { artist:"Haloo Helsinki!", song:"Beibi" },
  { artist:"Haloo Helsinki!", song:"Jos Mun Pokka Pettää" },
  { artist:"Haloo Helsinki!", song:"Maailman toisella puolen" },
  { artist:"Haloo Helsinki!", song:"Reiviluola" },
  { artist:"Harry Styles", song:"As It Was" },
  { artist:"Hassisen Kone", song:"Levottomat jalat" },
  { artist:"Hausmylly", song:"Ikävä Lokakuu" },
  { artist:"Hector", song:"Juodaan viinaa" },
  { artist:"Infernal", song:"From Paris to Berlin" },
  { artist:"Irina", song:"Kymmenen Kirosanaa" },
  { artist:"Irina", song:"Pokka" },
  { artist:"Indica", song:"Ikuinen Virta" },
  { artist:"Irwin Goodman", song:"Ei tippa tapa" },
  { artist:"Irwin Goodman", song:"Rentun ruusu" },
  { artist:"J. Karjalainen", song:"Mennyt mies" },
  { artist:"Jenni Vartiainen", song:"Ihmisten edessä" },
  { artist:"Jessie J", song:"Price Tag" },
  { artist:"Jet", song:"Are You Gonna Be My Girl" },
  { artist:"Joan Jett & the Blackhearts", song:"I Love Rock ‘n Roll" },
  { artist:"John Denver", song:"Take Me Home, Country Roads" },
  { artist:"Journey", song:"Don’t Stop Believin’" },
  { artist:"Juice Leskinen", song:"Viidestoista yö" },
  { artist:"Juice Leskinen", song:"Musta Aurinko Nousee" },
  { artist:"Justin Bieber feat. Nicki Minaj", song:"Beauty And A Beat" },
  { artist:"Justin Timberlake", song:"Can’t Stop the Feeling" },
  { artist:"Justin Timberlake", song:"SexyBack" },
  { artist:"JVG", song:"Amatimies" },
  { artist:"JVG", song:"Huominen On Huomenna" },
  { artist:"JVG", song:"Häissä" },
  { artist:"JVG", song:"Ikuinen Vappu" },
  { artist:"JVG", song:"Kran Turismo" },
  { artist:"JVG", song:"Mitä Mä Malagas" },
  { artist:"JVG", song:"Tarkenee" },
  { artist:"JVG", song:"Voitolla yöhön" },
  { artist:"KAJ", song:"Bara Bada Bastu" },
  { artist:"Kaija Koo", song:"Kaunis, Rietas, Onnellinen" },
  { artist:"Kaija Koo", song:"Supernaiset" },
  { artist:"Kaija Koo", song:"Tinakenkätyttö" },
  { artist:"Kaija Koo", song:"Vapaa" }

// JATKA LISTAA TÄHÄN SAMALLA FORMATTILLA
// (lyhensin tiedostoa jotta GitHub ei räjähdä viestissä 😄)
];
